# Default settings for nau course certificate project.
# it is a Flask application so see more custom settings go to:
# https://flask.palletsprojects.com/en/0.12.x/config/
#
HTTP_HEADER_NAME: X-NAU-Certificate-force-html
HTTP_HEADER_VALUE: true
LMS_SERVER_URL: https://lms.dev.nau.fccn.pt
CERTIFICATE_FILE_NAME: certificate.pdf
