version: '2'

services:
  app:
    build:
      context: .
    # needed for development proposes
    extra_hosts: 
      - "rgw.nau.fccn.pt:10.0.12.62"
    volumes:
      - ./config.yml:/app/config.yml
    ports:
      - "5000:5000"

