version: '3.8'

services:
  app:
    build:
      context: .
    # needed for development proposes
    volumes:
      - ./config.yml:/app/config.yml
      - ./digital_signature_dev:/app/digital_signature_dev
    ports:
      - "5000:5000"
    environment:
      - OPENEDX_LMS_URL=https://lms.dev.nau.fccn.pt
